# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 17:57
from __future__ import unicode_literals

from django.db import migrations
import csv

def add_player_data(apps, schema_editor):
    Player = apps.get_model("django_migrations", "Player")
    with open('players.csv') as infile:
        reader = csv.reader(infile)
        for row in reader:
            Player.objects.create(id = row[0], name = row[1], position = row[2], country = row[3], rating=row[4], age = row[5] )
    
class Migration(migrations.Migration):

    dependencies = [
        ('django_migrations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_player_data)
    ]
